C
      SUBROUTINE MSTAT5(LSP,MV,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
CD        CODED BY F.KIMURA
CP        MEAN VECTOR, COVARIANCE MATRIX NO EIGENVALU, EIGNEVECTOR NO
CP        KEISAN
C
CA        LSP : LEARNING SAMPLE VECTORS (I)
CA        MV : MEAN VECTOR (O)
CA        EVAL : COVARIANCE MATRIX NO EIGENVALUE (O)
CA        EVEC : COVARIANCE MATRIX NO EIGENVECTOR (O)
CA        WORK : SAGYOU HAIRETSU (WORK)
CA        N : FEATURE SIZE (I)
CA        M : LEARNING SAMPLE SIZE (I)
CA        ESP : SHUUSOKU JYOKEN (I)
CA        ILL : ILLEAGAL PARAMETER (O)
C
CS        CALL MSTAT5(LSP,MV,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
      REAL LSP(N,M),MV(N),EVAL(N),WORK(N),EVEC(N,N)
      CALL MSTAT2(LSP,MV,EVEC,N,M)
      ILL=1
      CALL HOQRUS(EVEC,N,N,EVAL,WORK,ESP,ILL)
C     WRITE(6,*) 'ILL',ILL,'EVAL',EVAL
C     WRITE(6,*) 'EVEC',EVEC
      RETURN
      END
