      SUBROUTINE BDFL2(IP,JP,ISX,ISY,LISTX,LISTY,
     -     LENG,LENG1,NBD,NC,KERR)
C  ***  BORDER FOLLOWING ALGORITHM
C  ***  FOLLOWING OF ALL BORDERS
C  ***
C  ***  IP(ISX,ISY)  : INPUT BINARY IMAGE
C  ***  JP(ISX,ISY)  : OUTPUT THREE-VALUED IMAGE
C  ***  LISTX(LENG) : ONE-DIMENSIONAL ARRAY (TEN NO X-ZAHYOU)
C  ***  LISTY(LENG) : ONE-DIMENSIONAL ARRAY (TEN NO Y-ZAHYOU)
C  ***  LENG1   :  LENGTH OF LISTX,LISTY
C  ***  NBD     :  NUMBER OF BORDER LINE
C  ***  NC  : CONNECTIVITY  (4  OR  8  )
C   ***  SUBROUTINE BODR1I O MOTIIRU
C  ***   SAKUSEI  S. YOKOI (BODR2I)
C  ***   S.  75.  11.  20
C  ****   MODIFIED BY S.TSURUOKA (1987.09.14)
      DIMENSION IP(ISX,ISY),JP(ISX,ISY),LISTX(LENG),LISTY(LENG)
      IF (KERR.LT.0) RETURN
      JSX=ISX
      JSY=ISY
      LENG0=LENG
      LENG1=1
      NBD=0
      KERR=0
      DO 16 IY=1,ISY
          DO 15 IX=1,ISX
              JP(IX,IY)=IP(IX,IY)
   15     CONTINUE
   16 CONTINUE
C  QQQ     LIST CLEAR
      DO 50 NN=1,LENG
          LISTX(NN)=0
          LISTY(NN)=0
   50 CONTINUE
C  QQQQQQQQQQQQQQQQQQ
C  AAA  1-LINE START TEN NO SEARCH
   11 CONTINUE
      DO 10 IY=1,ISY
          DO 10 IX=1,ISX
              IF(JP(IX,IY).NE.1) GO TO 10
              JP4=JP(IX-1,IY)*JP(IX+1,IY)*JP(IX,IY-1)*JP(IX,IY+1)
              IF(JP4.EQ.0) GO TO 20
   10 CONTINUE
C  AAAAAAAAAAAAAAAAAAAAAAAAAA
      GO TO 30
C  BBB  1-LINE  TRACKING
   20 CONTINUE
      IS=1
      IF(JP(IX-1,IY).EQ.0) IS=3
      IF(JP(IX+1,IY).EQ.0) IS=7
      IF(JP(IX,IY-1).EQ.0) IS=5
      IX0=IX
      IY0=IY
      CALL BDFL1(JP,JP,JSX,JSY,LISTX,LISTY,LENG0,LENG1,IX0,IY0,IS,
     &   NC,KERR)
      IF(KERR.EQ.-1) RETURN
      LENG1=LENG1+2
      NBD=NBD+1
CF**  BEYOND THE LENGTH OF THE LIST
      IF(LENG1.LE.LENG) GO TO 11
C  ERROR CODE GENERATION
C  LISTX AND LISTY HAVE OVERFLOWED
      KERR=-1
   30 CONTINUE
      LENG1=LENG1-1
      RETURN
      END
