      SUBROUTINE  BINARY(IA,I1,J1,IB,IT)
***
CS    CALL BINARY(IA,I1,J1,IB,IT)
***
CP    GAZOU DATA NO 2 CHIKA O OKONAU
***
CA    IA --- NYUURYOKU GAZOU (2 JIGEN HAIRETSU)
CA    I1 --- IA NO SEIGOU SUNPOU (DAI 1 SOEJI NO SUNPOU)
CA    J1 --- IA NO SEIGOU SUNPOU (DAI 2 SOEJI NO SUNPOU)
CA    IB --- SYUTSURYOKU GAZOU (2 JIGEN HAIRETSU)
CA    IT --- SHIKIICHI
***
CN    IA(I,J)  >= IT  --->  IB(I,J) = 1
CN    IA(I,J)  <  IT  --->  IB(I,J) = 0
***
CD   CODED    BY  S.MIURA     1984.10.01
CD   REVISED  BY  H.KAKENO    1985.06.17
***
      INTEGER IB(I1,J1),IA(I1,J1),IT
*C
      DO 10 J=1,J1
       DO 10 I=1,I1
         IF( IA(I,J) .GE. IT ) THEN
           IB(I,J)=1
         ELSE
           IB(I,J)=0
         END IF
*C
   10 CONTINUE
      RETURN
      END
