      FUNCTION CD1(X,MV,N)
C
CD        CODED BY F.KIMURA
CP        CITY BLOCK DISTANCE
C
CA        X : FEATURE VECTOR
CA        MV : MEAN VECTOR
CA        N : FEATURE SIZE
C
CS        CD1(X,MV,N)
C
      DIMENSION X(N),MV(N)
      REAL MV
      CD1=0.0
      DO 100 I=1,N
          CD1=CD1+ABS(X(I)-MV(I))
  100 CONTINUE
      RETURN
      END
