      REAL FUNCTION MQD3(X,MV,EVAL,EVEC,N,K,H)
C
CD        CODED BY F.KIMURA , CHANGED FROM MQD2 BY WAKA
CP        MODIFIED QUADRATIC DISCRIMINANT FUNCTION (3)
C
CA        X : FEATURE VECTOR
CA        MV : MEAN VECTOR
CA        EVAL : EIGENVALUES OF COVARIANCE MATRIX
CA        EVEC : EIGENVECTORS OF COVARIANCE MATRIX
CA        N : FEATURE SIZE
CA        K : KEISAN NI TSUKAU EIGENVECTOR NO KOSU
CA        H : CONSTANT
C
CS        MQD3(X,MV,EVAL,EVEC,N,K,H)
C
      REAL MV(N),EVAL(N),EVEC(N,K),X(N)
      SH=H
      IF (H.LE.0.0) THEN
          SH=0.0
          DO 10 I=K+1,N
              SH=SH+EVAL(I)
   10     CONTINUE
          SH=SH/(N-K)
      ENDIF
      MQD3=0.0
      DET=0.0
      SD=0.0
      DO 50 I=1,N
          SD=SD+(X(I)-MV(I))**2
   50 CONTINUE
      DO 100 I=1,K
          P=0.0
C          DET=DET+LOG(EVAL(I))
          DO 200 J=1,N
              P=P+EVEC(J,I)*(X(J)-MV(J))
  200     CONTINUE
          MQD3=MQD3+(1.0-SH/EVAL(I))*P*P
  100 CONTINUE
C      MQD3=(SD-MQD3)/SH+DET+LOG(SH)*(N-K)
      MQD3=(SD-MQD3)/SH
C     WRITE(6,*) MQD3
      RETURN
      END
