C
      REAL FUNCTION MS1(X,EVEC,N,K)
C
CD        CODED BY F.KIMURA
CP        FUKUGOU RUIJIDO (MULTIPLE SIMILARITY)
C
CA        X : FEATURE VECTOR
CA        EVEC : EIGENVECTOR OF AUTOCORELATION MATRIX
CA        N : FEATURE SIZE
CA        K : SHIKIBETSU NI TSUKAU EIGENVECTOR NO KOSU
C
CS        MS1(X,EVEC,N,K)
C
      DIMENSION X(N),EVEC(N,K)
      MS1=0.0
      DO 100 I=1,K
         S=0.0
         DO 200 J=1,N
            S=S+(EVEC(J,I)*X(J))
  200       CONTINUE
C         MS1=MS1+S**2
         MS1=MS1+S*S
  100    CONTINUE
      RETURN
      END
