C
      REAL FUNCTION MS2(X,EVAL,EVEC,N,K,BETA)
C
CD        CODED BY T.WAKA
CP        FUKUGOU RUIJIDO (MULTIPLE SIMILARITY)
C
CA        X : FEATURE VECTOR
CA        EVAL : EIGENVALUE
CA        EVEC : EIGENVECTOR OF AUTOCORELATION MATRIX
CA        N : FEATURE SIZE
CA        K : SHIKIBETSU NI TSUKAU EIGENVECTOR NO KOSU
CA        BETA : MS2 = (1-BETA)*MS2 - BETA*DET
C
CS        MS2(X,EIGENVALUE,EVEC,N,K)
C
      DIMENSION X(N),EVAL(N),EVEC(N,K)
      REAL DET,BETA
      MS2=0.0
      DET=0.0
      DO 100 I=1,K
         DET=DET+LOG(EVAL(I))
         S=0.0
         DO 200 J=1,N
            S=S+(EVEC(J,I)*X(J))
  200       CONTINUE
         MS2=MS2+S*S
  100    CONTINUE
      MS2=BETA*log(1-MS2) + DET
      RETURN
      END
