C
      SUBROUTINE MSTAT4N(LSP,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
CD        CODED BY F.KIMURA
CD        MODIFIED BY T.WAKA
CP        AUTOCORELATION MATRIX NO EIGENVALUE, EIGNEVECTOR NO
CP        KEISAN
C
CA        LSP : LEARNING SAMPLE VECTORS (I)
CA        EVAL : AUTOCORELATION MATRIX NO EIGENVALUE (O)
CA        EVEC : AUTOCORELATION MATRIX NO EIGENVECTOR (O)
CA        WORK : SAGYOU HAIRETSU (WORK)
CA        N : FEATURE SIZE (I)
CA        M : LEARNING SAMPLE SIZE (I)
CA        ESP : SHUUSOKU JYOKEN (I)
CA        ILL : ILLEAGAL PARAMETER (O)
C
CS        CALL MSTAT4N(LSP,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
      REAL LSP(N,M),EVAL(N),WORK(N),EVEC(N,N)
      REAL SUM
C
      DO 20 J=1,M
         SUM=0.0
         DO 10 I=1,N
            SUM=SUM+LSP(I,J)*LSP(I,J)
   10    CONTINUE
         SUM=1.0/SQRT(SUM)
         DO 15 I=1,N
            LSP(I,J)=LSP(I,J)*SUM
   15    CONTINUE
   20 CONTINUE
C      
      CALL MSTAT3(LSP,WORK,EVEC,N,M)
      ILL=1
      CALL HOQRUS(EVEC,N,N,EVAL,WORK,ESP,ILL)
      RETURN
      END
