C
      SUBROUTINE MSTAT4(LSP,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
CD        CODED BY F.KIMURA
CP        AUTOCORELATION MATRIX NO EIGENVALUE, EIGNEVECTOR NO
CP        KEISAN
C
CA        LSP : LEARNING SAMPLE VECTORS (I)
CA        EVAL : AUTOCORELATION MATRIX NO EIGENVALUE (O)
CA        EVEC : AUTOCORELATION MATRIX NO EIGENVECTOR (O)
CA        WORK : SAGYOU HAIRETSU (WORK)
CA        N : FEATURE SIZE (I)
CA        M : LEARNING SAMPLE SIZE (I)
CA        ESP : SHUUSOKU JYOKEN (I)
CA        ILL : ILLEAGAL PARAMETER (O)
C
CS        CALL MSTAT4(LSP,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
      REAL LSP(N,M),EVAL(N),WORK(N),EVEC(N,N)
      CALL MSTAT3(LSP,WORK,EVEC,N,M)
      ILL=1
      CALL HOQRUS(EVEC,N,N,EVAL,WORK,ESP,ILL)
      RETURN
      END
