C
      SUBROUTINE MSTAT5D(LSP,MV,EVAL,WORK,EVEC,N,M,ESP,ILL)
C
CD        CODED BY F.KIMURA
CP        MEAN VECTOR, COVARIANCE MATRIX NO EIGENVALU, EIGNEVECTOR NO
CP        KEISAN
C
CA        LSP : LEARNING SAMPLE VECTORS (I)
CA        MV : MEAN VECTOR (O)
CA        EVAL : COVARIANCE MATRIX NO EIGENVALUE (O)
CA        EVEC : COVARIANCE MATRIX NO EIGENVECTOR (O)
CA        WORK : SAGYOU HAIRETSU (WORK)
CA        N : FEATURE SIZE (I)
CA        M : LEARNING SAMPLE SIZE (I)
CA        ESP : SHUUSOKU JYOKEN (I)
CA        ILL : ILLEAGAL PARAMETER (O)
C
CS        CALL MSTAT5D(LSP,MV,EVAL,WORK,EVEC,N,M,DESP,ILL)
C
      REAL LSP(N,M),MV(N),EVAL(N),WORK(N),EVEC(N,N)
      REAL*8 DEVAL(1500),DWORK(1500),DEVEC(1500*1500)
      REAL*8 DESP
      CALL MSTAT2CD(LSP,MV,EVEC,N,M)
      ILL=1
      DO 20 J=1,N
         DO 10 I=1,N
            DEVEC((J-1)*N+I)=EVEC(I,J)
   10    CONTINUE
   20 CONTINUE
      DESP = ESP
      CALL HOQRUD(DEVEC,N,N,DEVAL,DWORK,DESP,ILL)
      DO 40 J=1,N
         EVAL(J)=DEVAL(J)
         DO 30 I=1,N
            EVEC(I,J)=DEVEC((J-1)*N+I)
   30    CONTINUE
   40 CONTINUE
C     WRITE(6,*) 'ILL',ILL,'EVAL',EVAL
C     WRITE(6,*) 'EVEC',EVEC
      RETURN
      END
