C
      SUBROUTINE MSTAT1(TSP,AMEAN,N,M)
C
CD        CODED BY F.KIMURA
CP        MEAN VECTOR NO KEISAN
C
CA        TSP : TRAINING SAMPLE VECTORS (I)
CA        AMEAN : MEAN VECTOR (O)
CA        N : FEATURE SIZE (I)
CA        M : TRAINING SAMPLE SIZE (I)
C
CS        CALL MSTAT1(TSP,AMEAN,N,M)
C
      DIMENSION TSP(N,M),AMEAN(N)
C
C     INITIALIZE
C
      DO 100 I=1,N
         AMEAN(I)=0.
  100    CONTINUE
      DO 200 I=1,M
         DO 300 J=1,N
            AMEAN(J)=AMEAN(J)+TSP(J,I)
  300       CONTINUE
  200    CONTINUE
      DO 400 I=1,N
         AMEAN(I)=AMEAN(I)/M
  400    CONTINUE
      RETURN
      END
