      SUBROUTINE NORMB7W(IA,I1,J1,IB,I2,J2,ILL)
CS    CALL NORMB7W(IA,I1,J1,IB,I2,J2,ILL)
CP****NORMALIZATION OF BINARY PATTERN
CP----  TATE YOKO HI WO ITTEI NI SURU
CP----  MOVEMENT OF PATTERN ... WAKU NO CHUSHIN
CA I   IA-------INPUT BINARY PATTERN (I1,J1)................I
CA O   IB-------OUTPUT NORMALIZED BINARY PATTERN (I2,J2,)...I
CA I   I2-------NORMALIZED SIZE OF X-DIRECTION..............I
CA       -------SCALE OF TRANSFORMATION AT X-DIRECTION......I
CA I   J2-------NORMALIZED SIZE OF Y-DIRECTION..............I
CA       -------SCALE OF TRANSFORMATION AT Y-DIRECTION......I
CE O   ILL------ERROR CODE   0,900,901,902,903 NSIZEB NI MOTOZUKU
CE              =900,901,902,903.... ALL 0 PATTERN
CD     CODED BY T.WAKABAYASHI
CM     2006.5.30
C*     EXTERNAL SYMBOL    NSIZEB, NTRNS3W
C*****
      INTEGER IA(I1,J1),IB(I2,J2)
C*****
      CALL NSIZEB(IA,I1,J1,IL,IR,JU,JD,ILL)
      IF(ILL.NE.0) RETURN
C*****
 1001 CONTINUE
C-----
      CALL NTRNS3W(IA,I1,J1,IB,I2,J2,IL,IR,JU,JD)
      RETURN
      END
