      SUBROUTINE NORMB2(IA,I1,J1,IB,I2,J2,CX,CY,ILL)
CS    CALL  NORMB2(IA,I1,J1,IB,I2,J2,CX,CY,ILL)
CP****NORMALIZATION OF BINARY PATTERN
CP----  TATE YOKO HI WO ITTEI NI SURU
CP----  MOVEMENT OF PATTERN ..... GYUUSHIN
CA I   IA-------INPUT BINARY PATTERN (I1,J1)................I
CA O   IB-------OUTPUT NORMALIZED BINARY PATTERN (I2,J2,)...I
CA I   I2-------SCALE OF TRANSFORMATION AT X-DIRECTION......I
CA I   J2-------SCALE OF TRANSFORMATION AT Y-DIRECTION......I
CA I   CX-------YOKO HOUKOU NO KIRIDASHI KEISUU ............R
CA I   CY-------TATE HOUKOU NO KIRIDASHI KEISUU ............R
CE O   ILL------ERROR CODE  0,900  GCENTB NI MOTOZUKU
CE              =900 ... ALL 0 PATTERN
CD     CODED BY H.MURASE
CM     1985.6.24  MODIFIED BY M.YOSIMURA
C*     EXTERNAL SYMBOL      GCENTB, NTRNS2
C*****
      INTEGER IA(I1,J1),IB(I2,J2)
C*****
C-----
      CALL GCENTB(IA,I1,J1,IGX,IGY,SVX,SVY,ILL)
      IF(ILL.NE.0) RETURN
      IXC=(I2+1)/2
      IYC=(J2+1)/2
      C11=2.*CX*SVX/I2
      C21=2.*CY*SVY/J2
      C12=IGX-C11*FLOAT(IXC)
      C22=IGY-C21*FLOAT(IYC)
      CALL NTRNS2(IA,I1,J1,IB,I2,J2,C11,C12,C21,C22)
      RETURN
      END
