      SUBROUTINE NTRNS2(IA,I1,J1,IB,I2,J2,C11,C12,C21,C22)
CS    CALL NTRNS2(IA,I1,J1,IB,I2,J2,C11,C12,C21,C22)
CP****TRANSFORMATION OF PATTERN
CA I   IA-------INPUT BINARY PATTERN       (I1,J1) .....I
CA I   I1-------X-HOKO DIMENSION........................I
CA I   J1-------Y-HOKO DIMENSION........................I
CA O   IB-------TRANSFORMED BINARY PATTERN (I2,J2)......I
CA I   I2-------X-HOKO DIMENSION........................I
CA I   J2-------Y-HOKO DIMENSION........................I
CA I   C11------CO-EFFICIENT OF TRANSFORMATION..........R
CA I   C12------CO-EFFICIENT OF TRANSFORMATION..........R
CA I   C21------CO-EFFICIENT OF TRANSFORMATION..........R
CA I   C22------CO-EFFICIENT OF TRANSFORMATION..........R
CD     CODED BY H.MURASE
CM     1985.6.24  MODIFIED BY M.YOSIMURA
C*****
      DIMENSION IA(I1,J1),IB(I2,J2)
C*****
      DO 100 I=1,I2
      ID=C11*FLOAT(I)+C12
      IF(ID.LT.1) ID=1
      IF(ID.GT.I1)ID=I1
      DO 100 J=1,J2
      JD=C21*FLOAT(J)+C22
      IF(JD.LT.1) JD=1
      IF(JD.GT.J1)JD=J1
      IB(I,J)=IA(ID,JD)
  100 CONTINUE
      RETURN
      END
