      SUBROUTINE SNORMB1(IA,I1,J1,IS1,JS1,IB,I2,J2,IS2,JS2,ILL)
CS    CALL SNORMB1(IA,I1,J1,IS1,JS1,IB,I2,J2,IS2,JS2,ILL)
CP****NORMALIZATION OF BINARY PATTERN
CP----  TATE YOKO HI WO ITTEI NI SURU
CP----  MOVEMENT OF PATTERN ... WAKU NO CHUSHIN
CA I   IA-------INPUT BINARY PATTERN (I1,J1)................I
CA O   IB-------OUTPUT NORMALIZED BINARY PATTERN (I2,J2,)...I
CA I   I2-------NORMALIZED SIZE OF X-DIRECTION..............I
CA       -------SCALE OF TRANSFORMATION AT X-DIRECTION......I
CA I   J2-------NORMALIZED SIZE OF Y-DIRECTION..............I
CA       -------SCALE OF TRANSFORMATION AT Y-DIRECTION......I
CE O   ILL------ERROR CODE   0,900,901,902,903 NSIZEB NI MOTOZUKU
CE              =900,901,902,903.... ALL 0 PATTERN
CD     CODED BY H.MURASE
CM     1985.6.24  MODIFIED BY M.YOSIMURA
C*     EXTERNAL SYMBOL    NSIZEB, NTRNS1
C*****
      INTEGER IA(IS1,JS1),IB(IS2,JS2)
C*****
      CALL SNSIZEB(IA,I1,J1,IS1,JS1,IL,IR,JU,JD,ILL)
      IF(ILL.NE.0) RETURN
C*****
 1001 CONTINUE
      C11=FLOAT(IR-IL)/(I2-1)
      C21=FLOAT(JD-JU)/(J2-1)
C-----
      CALL SNTRNS1(IA,I1,J1,IS1,JS1,IB,I2,J2,IS2,JS2,C11,IL,C21,JU)
      RETURN
      END
