      SUBROUTINE SUBED1(X,MV,N,ED1)
C
CD        CODED BY F.KIMURA
CP        EUCLID  DISTANCE
C
CA        X : FEATURE VECTOR
CA        MV : MEAN VECTOR
CA        N : FEATURE SIZE
CA        ED1 : SQUARE EUCLID DISTANCE
C
CS        SUBED1(X,MV,N,ED1)
C
      DIMENSION X(N),MV(N)
      REAL MV
      REAL ED1
      REAL TMP
      ED1=0.0
      DO 100 I=1,N
         TMP=X(I)-MV(I)
         ED1=ED1+TMP*TMP
  100    CONTINUE
      RETURN
      END
